### ISSUE TITLE
Relax upper bounds on dependencies

### ISSUE THREAD

**Issue by FranklinChen** [davdar/final-pretty-printer#6]
Using Stack with LTS-15.15 and GHC 8.8.3, I had to use `allow-newer` to build `final-pretty-printer`. Perhaps relax the upper bounds?

```
WARNING: Ignoring final-pretty-printer's bounds on ansi-terminal (==0.6.*); using ansi-terminal-0.10.3.
Reason: allow-newer enabled.
WARNING: Ignoring final-pretty-printer's bounds on base (>=4.3 && <4.10); using base-4.13.0.0.
Reason: allow-newer enabled.
WARNING: Ignoring final-pretty-printer's bounds on containers (==0.5.*); using containers-0.6.2.1.
Reason: allow-newer enabled.
WARNING: Ignoring final-pretty-printer's bounds on exceptions (==0.8.*); using exceptions-0.10.4.
Reason: allow-newer enabled.
```

**Comment by davdar** [comment]
Yes I think we should do this.

@david-christiansen, I've bumped the version numbers, which leads to compile errors because Semigroup is a new thing in new GHC versions, and required for every Monoid instance, which we make a few of.

I've gone through and added CPP macros to create the Semigroup instance when the GHC version is sufficiently high (`#if MIN_VERSION_base(4,9,0)` I think?).

There is now an issue in `/Text/PrettyPrint/Final/Demos/STLCDemo.hs` which uses operators like `/*/`. CPP must be enabled for this file in order to create the Semigroup instance for recent GHC versions, however when CPP is enabled it parses any `/*` as a CPP comment.

Solution 1: Bump everything to recent GHC versions, so no need for CPP
Solution 2: Leave the entire repo as is, and only work for old GHC versions
Solution 3: Rename the `/*/` operator to `|*|` (and likewise `/+/` to `|+|`, etc.)

My vote is 3, as those operators are just for demo purposes. Happy to fix and push if @david-christiansen agrees.
